export const QUICK_ACCESS_DEFAULT_SNAP_POINT = 0.75;
export const QUICK_ACCESS_FULL_SNAP_POINT = 1;

export const DRAWER_CONTENT_TOP_PADDING_EXPANDED_DELTA_PX = 40;
export const DRAWER_CONTENT_BACKDROP_BLUR_MAX_PX = 30;
export const DRAWER_CONTENT_BG_MAX_OPACITY = 0.8;
export const DRAWER_OVERLAY_MAX_OPACITY = 0.35;

export const DRAWER_SNAP_TRANSITION_LOCK_MS = 260;
export const DRAWER_SURFACE_LINKED_ANIMATION_MS = 620;
export const DRAWER_LAYOUT_LINKED_ANIMATION_MS = 320;

export const DRAWER_COLLAPSED_HEIGHT_VH = 88;
export const DRAWER_EXPANDED_HEIGHT_VH = 94;

export const RHYTHM_BACKGROUND_SCALE_AT_FULL_DRAWER = 1.1;
export const WHEEL_SESSION_GAP_MS = 140;
export const WHEEL_SNAP_THRESHOLD = 60;
